apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quakewatch.serviceAccountName" . }}
  labels:
    {{- include "quakewatch.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
